name: python-tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v5
      - name: Run unit tests
        working-directory: src/python
        run: uv run --python ${{ matrix.python-version }} --extra test --extra util pytest
