# This workflow runs the typescript implementation unit tests
name: ts-tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: src/ts
        run: npm install
      - name: Lint
        working-directory: src/ts
        run: npm run lint
      - name: Run unit tests
        working-directory: src/ts
        run: npm test
